apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: model
  namespace: ouiedire
spec:
  targets:
    - model/api/rest.yaml
    - model/component/www.yaml
    - model/system/ouiedire.yaml
  owner: default/ouiedire-net