apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: www
  namespace: ouiedire
  annotations:
    github.com/project-slug: constructions-incongrues/ouiedire
spec:
  type: website
  owner: ouiedire
  lifecycle: plesk-git
  dependsOn:
    - component:plesk/storage
    
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rest
  namespace: ouiedire
spec:
  type: openapi
  owner: ouiedire
  lifecycle: experimental
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: ouiedire API
    servers:
      - url: https://data.constructions-incongrues.net/ouiedire
  apiProvidedBy:
    - component:ivresse/directus
