---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ouiedire
  description: Le site ouiedire.net
  annotations:
    github.com/project-slug: constructions-incongrues/net.ouiedire.www
  links:
    - url: https://www.ouiedire.net
      title: ouiedire.net
      icon: public
    - url: https://plesk.pastis-hosting.net/smb/file-manager/list/domainId/64
      title: Gestionnaire de fichiers
      icon: folder
    - url: https://plesk.pastis-hosting.net/modules/ssh-terminal/?dom_id=64&site_id=64
      title: Terminal SSH
      icon: terminal
spec:
  type: website
  lifecycle: production
  owner: constructions
  system: ouiedire

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ouiedire
spec:
  owner: constructions

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ouiedire-storage
spec:
  type: blockstorage
  owner: constructions
  system: ouiedire
