apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: model
  namespace: ouiedire
spec:
  targets:
    - model/api/rest.yaml
    - model/component/website.yaml
    - model/resources/block.yaml
    - model/system/web.yaml
