apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: net.ouiedire.www
  annotations:
    github.com/project-slug: constructions-incongrues/net.ouiedire.www
  links:
    - url: https://www.ouiedire.net
      title: ouiedire.net
      icon: public
spec:
  type: other
  lifecycle: unknown
  owner: ouiedire
