apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: www
  namespace: ouiedire
  annotations:
    github.com/project-slug: constructions-incongrues/net.ouiedire.www
spec:
  type: website
  owner: default/ouiedire-net
  system: ouiedire
  lifecycle: plesk-git
  dependsOn:
    - component:plesk/storage